services:
  init:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: app
      args:
        INSTALL_DEV_DEPENDENCIES: 'false'

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: app

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: web

  queue:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: app

  scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: app

  reverb:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: app
