services:
  init:
    build: null
    image: ${APP_IMAGE}

  app:
    build: null
    image: ${APP_IMAGE}

  web:
    build: null
    image: ${WEB_IMAGE}

  queue:
    build: null
    image: ${APP_IMAGE}

  scheduler:
    build: null
    image: ${APP_IMAGE}

  reverb:
    build: null
    image: ${APP_IMAGE}
